Task1/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task1.Models;

namespace Task1.Controllers
{
    public class StoreController : Controller
    {
        Task1Entities db = new Task1Entities();

        // GET: Store
        public ActionResult Index()
        {

            
            var model = new List<Store>();

            using (var db = new Task1Entities())
            {

                var query = db.Store.Select(row => row);

                foreach (var item in query)
                {
                    Store store = new Store();


                    store.Store_Name = item.Store_Name;
                    store.Store_Address = item.Store_Address;
                    store.Id = item.Id;

                    model.Add(store);
                }

            }
            return View("StoreIndex",model);
        }

        public JsonResult List()
        {
            using (var db = new Task1Entities())
            {
                var customer = db.Store.Select(x => new
                {
                    x.Id,
                    x.Store_Name,
                    x.Store_Address,
                }).ToList();
                return Json(customer, JsonRequestBehavior.AllowGet);
            }
        }


        // GET: Store/Details/5
        public ActionResult Details(int id)
        {
            Product product = new Product();
            using (var db = new Task1Entities())
            {
                var query = db.Product.Where(row => row.Id==id);
                foreach (var item in query)

                {
                    
                    product.Product_Name = item.Product_Name;
                    product.Product_Price = item.Product_Price;
                    product.Id = item.Id;
                }

            }
                return View(product);
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        [HttpPost]
        public ActionResult Create(Store store)
        {

            try
            {
                // TODO: Add insert logic here

                using (var db = new Task1Entities())
                {

                    bool exist = db.Store.Where(x => x.Store_Name == store.Store_Name).Any();

                    Store str = new Store();
                    str.Store_Name = store.Store_Name;
                    str.Store_Address = store.Store_Address;


                    if (!exist) //check to updat eor create
                    {
                        db.Store.Add(str);
                    }
                    else
                    {
                        str = db.Store.SingleOrDefault(x => x.Store_Name == store.Store_Name);
                        str.Store_Name = store.Store_Name;
                        str.Store_Address = store.Store_Address;
                    }
                    // executes the commands to implement the changes to the database
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Store/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Delete/5
        public ActionResult Delete(int id)
        {
            Store store = new Store();
            using (var db = new Task1Entities())
            {
                var query = db.Store.Where(row => row.Id == id);
                foreach (var item in query)

                {
                    store.Store_Name = item.Store_Name;
                    store.Store_Address = item.Store_Address;
                    store.Id = item.Id;
                }

            }
            return View(store);
        }
        // POST: Store/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Store store)
        {
            try
            {
                // TODO: Add insert logic here

                using (var db = new Task1Entities())
                {

                    Store str= db.Store.SingleOrDefault(x => x.Id == store.Id);
                    db.Store.Remove(str);

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.InnerException);
                return View();
            }
        }

      

      

    }
}

Task1/Views/Store/Delete.cshtml
@model Task1.Store

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Store Details</h4>
        <table>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Store_Address)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Store_Name)
                </td>

            </tr>

            <tr>

                <td>
                    @Html.DisplayFor(model => model.Store_Address)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Store_Name)
                </td>


            </tr>

        </table> 

    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Task1/Views/Store/Details.cshtml
@model Task1.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            width: 100%;
            padding: 2px;
        }

        tr, td {
            border-top: 1px solid grey;
            border: 1px, solid;
            text-align: left;
            padding: 8px;
        }

        th {
            column-span: all;
        }
    </style>
</head>


<body>

    <h2>    Product </h2>

    @Html.ActionLink("Create", "Create", "store")

    <table>

        <tr>

            <th>@Html.LabelFor(model => Model.Id)</th>
            <th>@Html.LabelFor(model => Model.Product_Name)</th>
            <th>@Html.LabelFor(model => Model.Product_Price)</th>
            <th>Action(Edit)</th>
            <th>Action(Delete)</th>
            <th>
        </tr>

        <tr>

            <td>@Html.DisplayFor(model => Model.Id)</td>
            <td>@Html.DisplayFor(model => Model.Product_Name)</td>
            <td>@Html.DisplayFor(model => Model.Product_Price)</td>

            <td> @Html.ActionLink("Edit", "Edit", "Store") </td>
            <td> @Html.ActionLink("Delete", "Delete", "Store")</td>

        </tr>



        <tr>
            <td></td>
        </tr>

    </table>





    <div>
        @Html.ActionLink("Back to List", "Details")
    </div>

</body>

</html>

Task1/Views/Store/Edit.cshtml
@model Task1.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Task1/Views/Store/Index.cshtml
@model List<Product>
@{
    ViewBag.Title = "Index";
}

<html>
<head>
    <style>

        table {
            font-family: arial, sans-serif;
            width: 100%;
            padding:2px;
        }
        tr,td{
            border-top:1px solid grey;
            border : 1px, solid;
            text-align:left;
            padding: 8px;
        }
        th{
            column-span:all;
        }
      

    </style>

</head>

<body>

    <h2>    Product </h2>

    @Html.ActionLink("Create", "Create", "store")
   
    <table>

        <tr>
            <td> Name</td>
            <td> Price</td>
            <td></td>

        </tr>


        @foreach (var prod in Model)
            {
            <tr>
                <td>@prod.Product_Name</td>
                <td>@prod.Product_Price</td>
                <td>
                    <table>
                        <tr>
                            @Html.ActionLink("Edit", "Edit", "Store") |
                            @Html.ActionLink("Details", "Details", "Store",new {id=prod.Id },null)|
                            @Html.ActionLink("Delete", "Delete", "Store")

                        </tr>
                    </table>
                </td>


            </tr>
        }


        <tr>
            <td></td>
        </tr>

    </table>





    <div>
        @Html.ActionLink("Back to List", "Details")
    </div>

</body>

</html>

Task1/Views/Store/StoreIndex.cshtml
@model    List<Store>
@{
    ViewBag.Title = "Create";
}

<html>
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            width: 100%;
            padding: 2px;
        }

        tr, td {
            border-top: 1px solid grey;
            border: 1px, solid;
            text-align: left;
            padding: 8px;
        }

        th {
            column-span: all;
        }
    </style>

</head>

<body>

    <h2> Store Details </h2>
    <a id="CreateNew" href="#" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Create New</a>


    <div id="myModal" class="modal fade" role="dialog">

        <!-- Modal content-->

        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">


                <form id="ProdForm">

                    <div class="form-group">
                        <label for="Store Name">Store Name:</label>

                        <input type="text" class="form-control" id="StoreName" name="StoreName" value="" />
                    </div>
                    <div class="form-group">
                        <label for="Store Address ">Store Address:</label>
                        <input type="text" class="form-control" id="StoreAddress" name="Address">
                    </div>

                </form>

            </div>
            <div class="modal-footer">
                <input type="Reset" value="Submit" class="btn btn-primary" id="btnSubmit">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>

            </div>
        </div>

    </div>


    <script>


        $('#myModal').on('show.bs.modal', function (e) {
            var bookId = $(e.relatedTarget).data('book-id');


            $(e.currentTarget).find('input[name="StoreName"]').val(bookId);

        });

        $(Document).ready(function () {

            $("#btnSubmit").click(function () {

                var StoreName = $("#StoreName").val();
                var StoreAddress = $("#StoreAddress").val();

                var prodData = {
                    Store_Name: StoreName,
                    Store_Address: StoreAddress,
                };

                $.ajax({

                    type: "Post",
                    url: "/Store/Create",

                    data:prodData,
                    success: function () {

                        $("#myModal").modal("hide");
                        location.reload(true);
                    }

                });

            })

        })
  </script>


    <table>

        <tr>
            <td> Store Name</td>
            <td> Store Address</td>
            <td>Action(Edit)</td>
            <td>Action(Delete)</td>


        </tr>


       @foreach (var store in Model)
            {

             <tr>
                    <td>@store.Store_Name</td>
                    <td>@store.Store_Address</td>

                    <td><a href="#myModal" class="btn btn-warning" data-toggle="modal" data-book-id=@store.Store_Name>Edit</a></td>
                    <td>  @Html.ActionLink("Delete", "Delete", "Store", new { id = store.Id }, new { @class = "btn btn-danger" })</td>
             </tr>
           }

    </table>



    <div>
        @Html.ActionLink("Back to List", "Index", "Store")
    </div>

</body>

</html>